### ISSUE TITLE
[General issue]: Smart commits on board

### ISSUE THREAD

**Issue by mahyarmirrashed** [anastariqkhan/cz-conventional-changelog-jira-smart-commits#1]
I am working on a project board called APP at the moment. Our JIRA has been connected to our repository through the DCVS settings. From that point, I created some changes (added a README), used the `cz-conventional-changelog-jira-smart-commits` adapter and made the commit. It looked like this:

```txt
Commit preview:

   ┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐     
   │                                                                                                        │     
   │   docs(readme): APP-20 add readme                                                                      │     
   │                                                                                                        │     
   │   Add README file to provide high-level information about the repository contents and general layout   │     
   │   of items.                                                                                            │     
   │                                                                                                        │     
   │   APP-20 #time 2d 3h #qa #comment JIRA's integration with GitHub should be fully integrated now.       │     
   │                                                                                                        │     
   └────────────────────────────────────────────────────────────────────────────────────────────────────────┘ 
```

I then executed `git push` and the results were pushed to the repository. I then confirmed on GitHub that the changes were made. I then went to the settings on JIRA and manually refreshed and it showed, for the first time, some activity. However, when I went to the `APP-20` issue on our APP board, the issue had not changed positions. For context, that issue is a `test` type issue.

Please let me know if I did something wrong but my expectation was that by adding the `#qa` to the smart commit, we would move APP-20 from the TODO lane to the QA lane.

**Comment by anastariqkhan** [comment]
Hi @mahyarmirrashed,

You should have a workflow named 'qa' so that a ticket is transitioned in that state. The columns in the sprint can contain multiple workflows

https://confluence.atlassian.com/adminjiraserver/working-with-workflows-938847362.html#:~:text=A%20Jira%20workflow%20is%20a,workflows%20to%20create%20your%20own.

<img width="219" alt="Screenshot 2022-05-11 at 3 20 18 PM" src="https://user-images.githubusercontent.com/1443080/167828008-6d9e48ee-fe27-4275-9211-5b18aff62c51.png">
