### ISSUE TITLE
How does one enter time spent?

### ISSUE THREAD

**Issue by rpopp-fni-stl-com** [anastariqkhan/cz-conventional-changelog-jira-smart-commits#2]
I see in engine that there is an input type for time spent, but I do not see how to enable that.  Can you explain how that is set as a default for any commit please?

**Comment by Dima-Abramenko** [comment]
@rpopp-fni-stl-com ,
As I can see, "**time spent**" step is optional and can be enabled when you answer "**yes**" on "**Does this change affect any open issue?**" question only:

![image](https://user-images.githubusercontent.com/22980799/213664231-31c3c210-de8d-49af-8c60-6a715b7c5a4e.png)

And I cannot find any options to customize this behaivor for this particular adapter :) Therefore you can just fork it and update the behavior for "**time spent**" step or try to use an alternative **commitizen** adapter :)

**Comment by anastariqkhan** [comment]
It's already enabled by default, if you enter any time respective JIRA's time convention i.e. `1w 3d 2h 15m` 
it will reflect on the JIRA issue.
 e.g.:
 
```
refactor(userdata): MA-936 refactored user data
all user statuses handled via User class.
MA-936 #time 1d #in-review
```

would reflect like:

![Screenshot 2023-01-23 at 5 03 03 PM](https://user-images.githubusercontent.com/1443080/214035104-0d6c78e9-3ef8-4ffe-a635-74fbf659eb30.png)

**Comment by Dima-Abramenko** [comment]
@anastariqkhan agree with you - "**time**" step works as expected, but it's hard to say that the step is enabled by default :) 

I've checked your adapter recently and you still need to answer "**yes**" on "**Does this change affect any open issue?**" question to see "**time**" step as it's optional according to source code:
<img width="539" alt="Снимок экрана 2023-01-23 в 18 40 35" src="https://user-images.githubusercontent.com/22980799/214042176-b65e78c9-3385-4aa7-b8e4-51478caaacca.png">

Anyways, I love your adapter! It's one of the best for Сommitizen in npm, I guess :)

P.S. just wondering if it's possible to make this step constantly required, via some extra option, for example?

**Comment by anastariqkhan** [comment]
The purpose of making this optional is sometimes a devloper might not want to link any commit to a JIRA issue, then he simply would answer **_No_** to the question.
`Does this affect any open issues? `

**Comment by anastariqkhan** [comment]
Thanks @Dima-Abramenko for the appreciation 💯 means alot.
